@startuml

left to right direction
skinparam packageStyle rectangle

actor admin
actor user

user --|> admin

rectangle OtagoMentorMatcherWebsite {
  admin -- (log in)
  admin -- (edit profile)
  admin -- (view analytics)
  admin -- (export reports)
  admin -- (import data)
  admin -- (invite administrator users)
  admin -- (manage accounts)
  admin -- (terminate matches)

  (log in) .> (authenticate user) : <<require>>

}
@enduml